# Generated by Django 6.0.2 on 2026-02-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_id_copy',
            field=models.FileField(blank=True, null=True, upload_to='documents/guardian_ids/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
