# Generated by Django 6.0.2 on 2026-02-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0003_studentprofile_guardian_id_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sub_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
