# Generated by Django 6.0.2 on 2026-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0004_studentprofile_location_studentprofile_sub_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='sub_county',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='constituency',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='county',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_id_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='household_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sub_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='ward',
            field=models.CharField(default='', max_length=100),
        ),
    ]
