# Generated by Django 6.0.2 on 2026-02-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0007_developmentproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
