# Generated by Django 6.0.2 on 2026-02-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0008_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board/')),
                ('status', models.CharField(choices=[('serving', 'Serving'), ('previous', 'Previous')], default='serving', max_length=20)),
                ('period', models.CharField(help_text='e.g. 2022 - 2027', max_length=100)),
            ],
        ),
    ]
