# Generated by Django 6.0.2 on 2026-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0009_boardmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='academic_year',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('recommended', 'Recommended by Committee'), ('approved', 'Approved for Disbursement'), ('rejected', 'Rejected'), ('paid', 'Funds Disbursed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('committee', 'Committee Member'), ('admin', 'MP Office Admin'), ('super_admin', 'Super Admin')], db_index=True, default='student', max_length=20),
        ),
    ]
