# Generated by Django 6.0.2 on 2026-02-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0010_alter_application_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BursaryCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=20, unique=True)),
                ('planned_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
