# Generated by Django 6.0.2 on 2026-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0011_bursarycycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='resources/')),
                ('category', models.CharField(choices=[('guide', 'Student Guide'), ('form', 'Official Form'), ('report', 'Public Report'), ('policy', 'Policy Document')], default='guide', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='bursarycycle',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bursarycycle',
            name='planned_budget',
        ),
        migrations.RemoveField(
            model_name='bursarycycle',
            name='year',
        ),
    ]
