# Generated by Django 6.0.2 on 2026-02-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0012_downloadabledocument_remove_bursarycycle_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursarycycle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bursarycycle',
            name='planned_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bursarycycle',
            name='year',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='downloadabledocument',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
