# Generated by Django 6.0.2 on 2026-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0013_bursarycycle_is_active_bursarycycle_planned_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4'), ('Year 5', 'Year 5'), ('Year 6', 'Year 6')], default='', max_length=20),
        ),
    ]
